# Generated by Django 3.2.9 on 2024-05-10 07:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=255)),
                ('plan_type', models.CharField(max_length=100)),
                ('plan_description', models.CharField(max_length=255)),
                ('plan_monthly_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_max_signals_monthly', models.IntegerField()),
                ('plan_unlimited_trade_parameters', models.BooleanField(default=False)),
                ('plan_unlimited_features', models.BooleanField(default=False)),
                ('plan_max_brokers', models.IntegerField()),
                ('plan_currency', models.CharField(max_length=3)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
